- id: '1703666220313'
  alias: Börn á fætur
  description: 'Kveikir á LED borðum í barnaherbergjum með grænu ljósi þegar það má
    fara á fætur'
  trigger:
  - platform: time
    at: 08:00:00
  condition:
  - condition: time
    weekday:
    - mon
    - tue
    - wed
    - thu
    - fri
    - sat
    - sun
  action:
  - service: light.turn_on
    data:
      rgb_color:
      - 0
      - 255
      - 0
    target:
      entity_id: light.kids_led
  mode: single
- id: '1703666688636'
  alias: Börn háttatími
  description: 'Kveikir á LED borðum í barnaherbergjum með rauðu ljósi þegar það á
    að sofa'
  trigger:
  - platform: time
    at: '20:00:00'
  condition: []
  action:
  - service: light.turn_on
    target:
      entity_id: light.kids_led
    data:
      rgb_color:
      - 255
      - 0
      - 0
  mode: single
- id: '1703761516729'
  alias: Heimkoma
  description: 'Kveikir ljós þegar einhver kemur heim'
  trigger:
  - platform: state
    entity_id:
    - zone.home
    from: '0'
  condition: []
  action:
  - service: light.turn_on
    target:
      entity_id:
      - light.entryway
      - light.hallway_ceiling
      - light.bathroom
    data: {}
  mode: single
