- id: '1703666220313'
  alias: Guðrún á fætur
  description: Kveikir á LED borða hjá Guðrúnu með grænu ljósi þegar það má fara á fætur á virkum dögum
  trigger:
  - platform: time
    at: 07:00:00
  condition:
  - condition: time
    weekday:
    - mon
    - tue
    - wed
    - thu
    - fri
  action:
  - service: light.turn_on
    data:
      rgb_color:
      - 0
      - 255
      - 0
    target:
      entity_id: light.gudrun_led
  mode: single
- id: '1703666688636'
  alias: Guðrún háttatími
  description: Kveikir á LED borða hjá Guðrúnu með rauðu ljósi þegar það er kominn háttatími
  trigger:
  - platform: time
    at: '20:00:00'
  condition: []
  action:
  - service: light.turn_on
    target:
      entity_id: light.gudrun_led
    data:
      rgb_color:
      - 255
      - 0
      - 0
  mode: single
- id: '1703761516729'
  alias: Heimkoma
  description: Kveikir ljós þegar einhver kemur heim
  trigger:
  - platform: state
    entity_id:
    - zone.home
    from: '0'
  condition: []
  action:
  - service: light.turn_on
    target:
      entity_id:
      - light.entryway
      - light.hallway_ceiling
      - light.bathroom
    data: {}
  mode: single
- id: '1703959289894'
  alias: Anaya á fætur
  description: Kveikir á LED borða hjá Anayu með grænu ljósi þegar það má fara á fætur á virkum dögum
  trigger:
  - platform: time
    at: 07:00:00
  condition:
  - condition: time
    weekday:
    - mon
    - tue
    - wed
    - thu
    - fri
  action:
  - service: light.turn_on
    data:
      rgb_color:
      - 0
      - 255
      - 0
      brightness_pct: 1
    target:
      entity_id: light.anaya_led
  mode: single
