homeassistant:
  name: Eyrarlundur 4
  latitude: 64.322772
  longitude: -22.042609
  elevation: 10
  unit_system: metric
  currency: ISK
  country: IS
  time_zone: Atlantic/Reykjavik

# Loads default set of integrations. Do not remove.
default_config:

# Load frontend themes from the themes folder
frontend:
  themes: !include_dir_merge_named themes

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
light: !include lights.yaml
zone: !include zones.yaml

lovelace:
  mode: yaml