homeassistant:
  name: Eyrarlundur 4
  latitude: 64.322772
  longitude: -22.042609
  elevation: 10
  unit_system: metric
  currency: ISK
  country: IS
  time_zone: Atlantic/Reykjavik

# Loads default set of integrations. Do not remove.
default_config:

# Load frontend themes from the themes folder
frontend:
  themes: !include_dir_merge_named themes

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
light: !include lights.yaml
zone: !include zones.yaml
rest: !include veitur.yaml

lovelace:
  resources:
    - url: /local/mushroom.js
      type: module
    - url: /hacsfiles/apexcharts-card/apexcharts-card.js
      type: module
    - url: /hacsfiles/button-card/button-card.js
      type: module
    - url: /local/card-mod.js
      type: module
  mode: yaml
  dashboards:
    lovelace-desktop:
      mode: yaml
      filename: ui-lovelace-desktop.yaml
      title: Desktop
      icon: mdi:monitor
      show_in_sidebar: true

template: !include template.yaml

shell_command:
  backfill_veitur: >-
    python3 /config/scripts/backfill_veitur.py

utility_meter:
  chargie_monthly_energy:
    source: sensor.chargie_energy_meter
    cycle: monthly
