resources:
    - url: /local/mushroom.js
      type: module

views:
  - !include views/mobile/home.yaml
  - !include views/mobile/master.yaml
  - !include views/mobile/anaya.yaml
  - !include views/mobile/gudrun.yaml
  - !include views/mobile/office.yaml
  - !include views/mobile/bathroom.yaml
  - !include views/mobile/livingroom.yaml
  - !include views/mobile/washingroom.yaml
  - !include views/mobile/entryway.yaml
  - !include views/mobile/hallway.yaml
  - !include views/mobile/kitchen.yaml
  - !include views/mobile/diningroom.yaml
  - !include views/mobile/sittingroom.yaml