resources:
    - url: /local/mushroom.js
      type: module

views:
  - title: Home
    cards:
      - type: horizontal-stack
        cards:
          - type: tile
            entity: person.kari
            vertical: true
            show_entity_picture: true
            hide_state: false
          - type: tile
            show_entity_picture: true
            vertical: true
            entity: person.magga
          - type: tile
            entity: person.anaya
            vertical: true
            show_entity_picture: true
      - type: custom:mushroom-title-card
        title: ''
        subtitle: Rými
      - type: horizontal-stack
        cards:
          - type: tile
            entity: light.master
            name: Hjón
            vertical: true
            tap_action:
              action: navigate
              navigation_path: master
            double_tap_action:
              action: more-info
          - type: tile
            entity: light.gudrun
            name: Guðrún
            vertical: true
            tap_action:
              action: navigate
              navigation_path: gudrun
            double_tap_action:
              action: more-info
          - type: tile
            entity: light.anaya
            name: Anaya
            vertical: true
            tap_action:
              action: navigate
              navigation_path: anaya
            double_tap_action:
              action: more-info
          - type: tile
            entity: light.office
            name: Skrifstofa
            vertical: true
            tap_action:
              action: navigate
              navigation_path: office
            double_tap_action:
              action: more-info
      - type: horizontal-stack
        cards:
          - type: tile
            entity: light.bathroom
            name: Bað
            vertical: true
            tap_action:
              action: navigate
              navigation_path: bathroom
            double_tap_action:
              action: more-info
          - type: tile
            entity: light.livingroom
            name: Sjónvarp
            vertical: true
            tap_action:
              action: navigate
              navigation_path: livingroom
            double_tap_action:
              action: more-info
          - type: tile
            entity: light.washingroom
            name: Þvottur
            vertical: true
            tap_action:
              action: navigate
              navigation_path: washingroom
            double_tap_action:
              action: more-info
          - type: tile
            entity: light.kitchen
            name: Eldhús
            vertical: true
            tap_action:
              action: navigate
              navigation_path: kitchen
            double_tap_action:
              action: more-info
      - type: horizontal-stack
        cards:
          - type: tile
            entity: light.entryway
            name: Forstofa
            vertical: true
            tap_action:
              action: navigate
              navigation_path: entryway
            double_tap_action:
              action: more-info
          - type: tile
            entity: light.hallway
            name: Gangur
            vertical: true
            tap_action:
              action: navigate
              navigation_path: hallway
            double_tap_action:
              action: more-info
          - type: tile
            entity: light.diningroom
            name: Borðstofa
            vertical: true
            tap_action:
              action: navigate
              navigation_path: diningroom
            double_tap_action:
              action: more-info
          - type: tile
            entity: light.sittingroom
            name: Stofa
            vertical: true
            tap_action:
              action: navigate
              navigation_path: sittingroom
            double_tap_action:
              action: more-info
  - title: Hjón
    path: master
    badges: []
    cards:
      - type: custom:mushroom-title-card
        title: Hjónaherbergi
  - title: Anaya
    path: anaya
    icon: ''
    badges: []
    cards:
      - type: custom:mushroom-title-card
        title: Anaya
      - type: custom:mushroom-title-card
        title: ''
        subtitle: Ljós
      - type: horizontal-stack
        cards:
          - type: tile
            entity: light.anaya
            name: Öll
            vertical: true
          - type: tile
            entity: light.anaya_ceiling
            name: Loft
            vertical: true
          - type: tile
            entity: light.anaya_wall
            name: Veggur
            vertical: true
          - type: tile
            entity: light.anaya_led
            vertical: true
            name: LED
  - title: Guðrún
    path: gudrun
    badges: []
    cards:
      - type: custom:mushroom-title-card
        title: Guðrún
      - type: custom:mushroom-title-card
        title: ''
        subtitle: Ljós
      - type: horizontal-stack
        cards:
          - type: tile
            entity: light.gudrun
            name: Öll
            vertical: true
          - type: tile
            entity: light.gudrun_ceiling
            name: Loft
            vertical: true
          - type: tile
            entity: light.gudrun_wall
            name: Veggur
            vertical: true
          - type: tile
            entity: light.gudrun_led
            name: LED
            vertical: true
  - title: Skrfistofa
    path: office
    badges: []
    cards:
      - type: custom:mushroom-title-card
        title: Skrifstofa
      - type: custom:mushroom-title-card
        title: Prentari
      - type: tile
        entity: sensor.canon_mg7500_series
        vertical: false
        state_content:
          - state
          - last-changed
      - type: horizontal-stack
        cards:
          - type: tile
            entity: sensor.canon_mg7500_series_black_bk
            name: BK
            vertical: true
            color: black
          - type: tile
            entity: sensor.canon_mg7500_series_gray
            vertical: true
            name: GY
            color: grey
          - type: tile
            entity: sensor.canon_mg7500_series_yellow
            name: 'Y'
            vertical: true
            color: yellow
          - type: tile
            entity: sensor.canon_mg7500_series_black_pgbk
            vertical: true
            name: PGBK
            color: black
          - type: tile
            entity: sensor.canon_mg7500_series_cyan
            name: C
            color: cyan
            vertical: true
          - type: tile
            name: M
            color: pink
            vertical: true
            entity: sensor.canon_mg7500_series_magenta
  - title: Bað
    path: bathroom
    badges: []
    cards:
      - type: custom:mushroom-title-card
        title: Baðherbergi
      - type: custom:mushroom-title-card
        title: ''
        subtitle: Ljós
      - type: horizontal-stack
        cards:
          - type: tile
            entity: light.bathroom
            name: Öll
            vertical: true
          - type: tile
            entity: light.bathroom_mirror
            vertical: true
          - type: tile
            entity: light.bathroom_sink
            vertical: true
          - type: tile
            entity: light.bathroom_bath_shower
            name: Bað/sturta
            vertical: true
  - title: Sjónvarp
    path: livingroom
    badges: []
    cards:
      - type: custom:mushroom-title-card
        title: Sjónvarpshol
      - type: custom:mushroom-title-card
        title: ''
        subtitle: Ljós
      - type: horizontal-stack
        cards:
          - type: tile
            entity: light.livingroom
            vertical: true
          - type: tile
            entity: light.livingroom_ceiling_front
            name: Fremri
            vertical: true
          - type: tile
            entity: light.livingroom_ceiling_back
            name: Aftari
            vertical: true
      - graph: line
        type: sensor
        detail: 2
        entity: sensor.hreyfiskynjari_v_bad_lux
        icon: light
  - title: Þvottur
    path: washingroom
    badges: []
    cards:
      - type: custom:mushroom-title-card
        title: Þvottahús
      - type: custom:mushroom-title-card
        title: ''
        subtitle: Ljós
      - type: horizontal-stack
        cards:
          - type: tile
            entity: light.washingroom
            name: Öll
            vertical: true
          - type: tile
            entity: light.washingroom_cabinets
            name: Innrétting
            vertical: true
          - type: tile
            entity: light.washingroom_ceiling
            name: Loft
            vertical: true
  - title: Forstofa
    path: entryway
    badges: []
    cards:
      - type: custom:mushroom-title-card
        title: Forstofa
  - title: Gangur
    path: hallway
    badges: []
    cards:
      - type: custom:mushroom-title-card
        title: Gangur
      - type: custom:mushroom-vacuum-card
        entity: vacuum.e4
        icon_animation: true
        fill_container: false
        commands:
          - start_pause
          - return_home
          - locate
        tap_action:
          action: more-info
  - title: Eldhús
    path: kitchen
    badges: []
    cards:
      - type: custom:mushroom-title-card
        title: Eldhús
      - type: custom:mushroom-title-card
        title: ''
        subtitle: Eldhús
      - type: horizontal-stack
        cards:
          - type: tile
            entity: light.kitchen
            name: Öll
            vertical: true
          - type: tile
            entity: light.kitchen_cabinets
            name: Innrétting
            vertical: true
          - type: tile
            entity: light.kitchen_ceiling
            name: Loft
            vertical: true
          - type: tile
            entity: light.kitchen_island
            name: Eyja
            vertical: true
  - title: Borðstofa
    path: diningroom
    badges: []
    cards:
      - type: custom:mushroom-title-card
        title: Borðstofa
  - title: Stofa
    path: sittingroom
    badges: []
    cards:
      - type: custom:mushroom-title-card
        title: Stofa
      - type: custom:mushroom-title-card
        title: ''
        subtitle: Ljós
      - type: horizontal-stack
        cards:
          - type: tile
            entity: light.sittingroom
            name: Öll
            vertical: true
          - type: tile
            entity: light.sittingroom_sofa_table
            vertical: true
          - type: tile
            entity: light.sittingroom_sliding_door
            vertical: true
